she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import CategoryView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('favourite/', views.favourite_post_list, name='favourite_post_list'),
    path('add-category/', views.AddCategoryView.as_view(),name='addCategory'),
    path('<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('<int:pk>/comment', views.AddCommentView.as_view(),name='addComment'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('<int:pk>/like', views.like_post, name='like'),
    path('<int:pk>/favourite_post', views.favourite_post, name='favourite_post'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, EditAccountView, ProfileView, PasswordsChangeView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),
name='createAccount'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/edit', EditAccountView.as_view(), name='editAccount'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html')),
]

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    name = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank = True, null=True)
    email = models.TextField(blank = True, null=True)
    profile_picture = models.URLField(blank = True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)


    def __str__(self):
        return self.username

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'email', 'bio', 'profile_picture', 'linkedin', 'instagram', 'github',]
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control form-item', 'placeholder': 'Enter your name'}),
            'username': forms.TextInput(attrs={'class':'form-control form-item', 'placeholder':'Enter a username'}),
            'email': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter your email'}),
            'bio': forms.Textarea(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a bio'}),
            'profile_picture': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder':'Enter a URL'}),
            'linkedin': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your LinkedIn'}),
            'instagram': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your Instagram'}),
            'github': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your GitHub'}),
            }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'email', 'bio', 'profile_picture', 'linkedin', 'instagram', 'github',]
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control form-item', 'placeholder': 'Enter your name',}),
            'username': forms.TextInput(attrs={'class':'form-control form-item', 'placeholder':'Enter a username'}),
            'email': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter your email'}),
            'bio': forms.Textarea(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a bio'}),
            'profile_picture': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder':'Enter a URL'}),
            'linkedin': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your LinkedIn'}),
            'instagram': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your Instagram'}),
            'github': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder': 'Enter a URL to your GitHub'}),
            }

# Django has inherent properties for UserCreationForm and UserChange Form, creating Custom users allows us to make changes to things that already exist

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from .models import CustomUser
from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm
from news.models import NewsStory

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class ProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    context_object_name = 'user'
    # def get_success_url(self):
    #     return reverse_lazy('users:profile', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])

        return context

class EditAccountView(generic.UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    context_object_name = 'createAccount'
    template_name = 'users/createAccount.html'
    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.object.id})

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('news:index')
    # def get_success_url(self):
    #     return reverse_lazy('users:editAccount', kwargs={'pk': self.object.id})

she_codes_news/users/templates/users/createAccount.html
{% extends "base.html" %}
{% block title %} Create A New Account {% endblock %}
{% load static %} {% block stylesheets %}


{% endblock %} {% block content %}
{% if request.user.is_authenticated %}
    <h2>Edit Account</h2>
{% else %}
    <h2>Create Account</h2>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="form-wrapper">
    {{ form.as_p }}
    {% if request.user.is_authenticated %}
        <button type="submit" class="accent-button">Save</button>
    {% else %}
        <button type="submit" class="accent-button">Create Account</button>
    {% endif %}
    </div>


</form>
{% endblock %}

<!--newaccount, seconduser@example.com, qwerty345@, bob3, qwerty345$-->

<!--cross site request forgery - security feature. Makes it harder for people to steal your credentials/trick you into clicking on their website?? -->

<!-- Most viewed stories, what's new, welcome message, keyword/title search function, favourites/saved/read, history of read stories, share function, related stories, comments, bookmarks, tags, ratings, sorting, accessibility?. Ratings, tags, top content, bookmarks, search, share on social media - easy. ratings - harder-->

she_codes_news/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="profile-wrapper">
<h2>{{ user.name|capfirst }}</h2>
{% if not user.profile_picture %}
      <img src="https://picsum.photos/600" class="profile-picture">
    {% else %}
      <img src="{{ user.profile_picture }}" class="profile-picture"/>
    {% endif %}
<p class="profile-bio">{{ user.bio }}</p>
<div>
    <ul class="contact-icons">
        {% if not user.email %}
          <li><a href="#"><i class="fa-solid fa-envelope"></i></a></li>
        {% else %}
          <li><a href="mailto:{{ user.email }}" target="_blank"><i class="fa-solid fa-envelope"></i></a></li>
        {% endif %}
        {% if not user.linkedin %}
          <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
        {% else %}
          <li><a href="{{ user.linkedin }}" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
        {% endif %}
        {% if not user.instagram %}
          <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
        {% else %}
          <li><a href="{{ user.instagram }}" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
        {% endif %}
        {% if not user.github %}
          <li><a href="#"><i class="fa-brands fa-github"></i></a></li>
        {% else %}
          <li><a href="{{ user.github }}" target="_blank"><i class="fa-brands fa-github"></i></a></li>
        {% endif %}

    </ul>
</div>

{% if request.user.id == user.id %}
<div class="favourites-link">
<a href="{% url 'news:favourite_post_list' %}">Favourites</a>
</div>
{% endif %}

<div id="all-stories">
  <h4>Stories by {{user.name|capfirst}}</h4>

  {% if stories %} 
  {% for story in stories %} 
    {% include "news/storyCard.html" with story=story position=forloop.counter %}
  {% endfor %} {% else %}
  <p class="back-up-text">No stories are available.</p>
  {% endif %}
</div>
{% if request.user.id == user.id %}
  <a href="{% url 'users:editAccount' request.user.id %}" class="accent-button">Edit Account</a>
{% endif %}
</div>
{% endblock %}