she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import CategoryView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('favourite/', views.favourite_post_list, name='favourite_post_list'),
    path('add-category/', views.AddCategoryView.as_view(),name='addCategory'),
    path('<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('<int:pk>/comment', views.AddCommentView.as_view(),name='addComment'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('<int:pk>/like', views.like_post, name='like'),
    path('<int:pk>/favourite_post', views.favourite_post, name='favourite_post'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, EditAccountView, ProfileView, PasswordsChangeView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),
name='createAccount'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/edit', EditAccountView.as_view(), name='editAccount'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html')),
]

she_codes_news/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>She Codes News</title>
    <meta name="description" content="" />
    <meta name="author" content="Hayley van Waas" />
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/24f16ae55e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    {% block stylesheets %}{% endblock %}
  </head>

  <body>
    <header>
      <div id="header-text">
      </div>
      <!-- include nav here -->
      {% include './nav.html' %}
    </header>
    {% block content %}{% endblock %}

    <!-- content blocks here -->
  </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a id="header-link" href="{% url 'news:index' %}">
        <h1>She {Codes} News</h1>
    </a>
    <ul class="nav-bar">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'users:profile' request.user.id %}">My Profile</a></li>
        <li><a href="{% url 'news:newStory' %}">Write New Story</a></li>
        <li><a href="{% url 'news:addCategory' %}">Create New Category</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'users:createAccount' %}">Create Account</a></li>
        {% endif %}
    </ul>
</nav>

<!-- double curly braces - this is a templating language, Jinga2. Allows dynamic content into HTML. % are for ifelse/for statements -->