she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import CategoryView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('favourite/', views.favourite_post_list, name='favourite_post_list'),
    path('add-category/', views.AddCategoryView.as_view(),name='addCategory'),
    path('<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('<int:pk>/comment', views.AddCommentView.as_view(),name='addComment'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('<int:pk>/like', views.like_post, name='like'),
    path('<int:pk>/favourite_post', views.favourite_post, name='favourite_post'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, EditAccountView, ProfileView, PasswordsChangeView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),
name='createAccount'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/edit', EditAccountView.as_view(), name='editAccount'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html')),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from users.models import CustomUser

class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name



class NewsStory(models.Model):
    class Meta:
        ordering = ['-pub_date']
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    # author = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(null=True)
    category = models.CharField(max_length=200, default='uncategorised')
    liked_by = models.ManyToManyField(CustomUser, related_name='liked_stories', blank=True )
    favourite = models.ManyToManyField(CustomUser, related_name='favourite', blank=True)


class Comment(models.Model):
    post = models.ForeignKey(NewsStory, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Comment, Category

choices = Category.objects.all().values_list('name','name')

choice_list = []

for item in choices:
    choice_list.append(item)


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'category', 'image_url']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control form-item', 'placeholder': 'Enter a title',}),
            'pub_date': forms.DateTimeInput(format='%Y-%m-%dT%H:%M', attrs={'class':'form-control form-item', 'placeholder':'Select a date','type':'datetime-local'}),
            'content': forms.Textarea(attrs={'class': 'form-control form-item', 'placeholder': 'Enter some text'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control form-item', 'placeholder': 'Select a category'}),
            'image_url': forms.TextInput(attrs={'class': 'form-control form-item', 'placeholder':'Enter a URL'}),
            }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets = {
          'name': forms.TextInput(attrs={'placeholder':"Enter your name", 'label':'name', 'class':'form-item',}), 
          'body': forms.Textarea(attrs={'placeholder':"Enter some text", 'label':'body','class':'form-item',}),
        
    }

#form validate method so that future dates can't be selected, show stories for dates in the past

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy, reverse 
from .models import NewsStory, Comment, Category
from .forms import StoryForm, CommentForm
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        # context['old_stories'] = NewsStory.objects.all().order_by('pub_date') [:5]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')

        # liked_story = get_object_or_404(NewsStory, id=self.kwargs['pk'])
        # total_likes = liked_story.total_likes()
        # context['total_likes'] = total_likes

        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
    # is_favourite = False

    # def story_detail(request, id):
    #     if story.likes.filter(id=request.user.id).exists():

class AddStoryView(generic.CreateView):
    model = NewsStory
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# def favourite_post(request, id):
#     story = get_object_or_404(NewsStory, id=id)
#     if story.favourite.filter(id = request.user.id).exists():
#         story.favourite.remove(request.user)
#     else: 
#         story.favourite.add(request.user)
#     return redirect('news:story', pk=story.id)

@login_required
def favourite_post(request, pk):
    story = get_object_or_404(NewsStory, pk=pk)
    user = request.user
    if story.favourite.filter(id=user.id).exists():
        story.favourite.remove(user)
    else:
        story.favourite.add(user)
    return redirect('news:story', pk=story.id)

def favourite_post_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {
        'favourite_posts': favourite_posts
    }
    return render(request, 'news/favourite_post_list.html', context)

@login_required
def like_post(request, pk):
    story = get_object_or_404(NewsStory, pk=pk)
    user = request.user
    if story.liked_by.filter(id=user.id).exists():
        story.liked_by.remove(user)
    else:
        story.liked_by.add(user)
    return redirect('news:story', pk=story.id)


def CategoryView(request, cats):
    category_posts = NewsStory.objects.filter(category=cats)
    return render(request, 'news/categories.html', {'cats':cats, 'category_posts':category_posts})

class AddCategoryView(generic.CreateView):
    model = Category
    # form_class = StoryForm
    # context_object_name = 'storyForm'
    template_name = 'news/add_category.html'
    fields = "__all__"
    success_url = reverse_lazy('news:index')

    # success_url = reverse_lazy('news:index')

class AddCommentView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'news/add_comment.html'
    success_url = reverse_lazy('news:index')
    # def get_success_url(self):
    #     return reverse_lazy('news:story', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class EditStoryView(generic.UpdateView):
    form_class = StoryForm
    model = NewsStory
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

she_codes_news/news/templates/news/add_category.html
{% extends "base.html" %}
{% block title %} Create A New Blog Category {% endblock %}
{% load static %} {% block stylesheets %}


{% endblock %} {% block content %}


<form action="" method="post" class="create-category-form">

    {% csrf_token %}
    <h2>Add Category</h2>
    <div class="special-form">
    <div class="form-wrapper">
        {{ form.as_p }}
        <input type="submit" value="Submit" class="accent-button">
        <a href="{% url 'news:index' %}" class="accent-button">Back</a>
    </div>
    </div>
</form>


{% endblock %}

she_codes_news/news/templates/news/add_comment.html
{% extends "base.html" %}
{% block title %} Comment on Blog Post {% endblock %}
{% load static %} {% block stylesheets %}


{% endblock %} {% block content %}


<form action="" method="post" class="add-comment-form">

    {% csrf_token %}
    <h2>Add A Comment</h2>
    <div class="form-wrapper">
    {{ form.as_p }}
    </div>
    <button class="accent-button">Add Comment</button>
    <a href="{% url 'news:index' %}" class="accent-button">Back</a>
</form>



{% endblock %}

she_codes_news/news/templates/news/categories.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}

{% endblock %} {% block content %}

<h2 class="category-heading">Category: {{ cats }}
</h2>

{% for story in category_posts %}
    <div id="all-stories">
        <div class="story-card">
            <a href="{% url 'news:story' story.id %}">
                {% if story.image_url != null %}
                    <img src={{ story.image_url }} />
                {% else %}
                    <img src="https://picsum.photos/600" />
                {% endif %}
            <div class="story-card-text">
                <p class="story-card-date">{{ story.pub_date }}</p>
                <h3>{{ story.title }}</h3>  
                <a href='{% url "news:category" story.category %}' class="story-card-category">{{ story.category }}</a>
                <a href="#" class="story-card-author">{{ story.author }}</a>
            
            </div>
            </a>
        </div>
    </div>

{% endfor %}

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% block title %} Create A New Blog Post {% endblock %}
{% load static %} {% block stylesheets %}


{% endblock %} {% block content %}


<form action="" method="post" class="create-story-form">

    {% csrf_token %}
    <h2>New blog post</h2>
    <div class="form-wrapper">
    {{ form.as_p }}
    <input type="submit" value="Submit" class="accent-button">
    <a href="{% url 'news:index' %}" class="accent-button">Back</a>
    </div>

</form>


{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% block title %} Delete A Post {% endblock %}
{% block content %}



<form action="" method="post">

    {% csrf_token %}
    <h2>Delete Post</h2>
    <div class="form-wrapper">
    <p>Are you sure you want to delete this post?</p>
    <button class="accent-button">Delete Post</button>
    <a href="{% url 'news:index' %}" class="accent-button">Back</a>
    </div>
</form>



{% endblock %}

she_codes_news/news/templates/news/favourite_post_list.html
{% extends "base.html" %}
{% block title %} Favourites {% endblock %}
{% block content %}

<div class="favourites-wrapper">
<div id="all-stories">
<h3 class="favourites-heading">Your Favourites</h3>
{% if favourite_posts %} 
{% for story in favourite_posts%}
{% include "news/storyCard.html" with story=story position=forloop.counter %}
  {% endfor %} {% else %}
  <p class="back-up-text">You don't currently have any favourite posts</p>
  {% endif %}
</div>
</div>



{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}

{% endblock %} {% block content %}

<div class="header-text">
  <span class="word-1">She</span><span class="word-2"> {Codes}</span><span class="word-3"> News</span>
</div>
<h2>Latest News</h2>

<div id="latest-stories">
  {% if latest_stories %} 
  {% for story in latest_stories %} 
    {% include "./storyCard.html" with story=story position=forloop.counter %}
  {% endfor %} {% else %}
  <p>No stories are available.</p>
  {% endif %}
</div>

<h2>All Stories</h2>

<div id="all-stories">
  {% if latest_stories %} 
  {% for story in all_stories %} 
    {% include "./storyCard.html" with story=story %}
  {% endfor %} {% else %}
  <p>No stories are available.</p>
  {% endif %}
</div>

{% endblock %}

<!--use same logic from login/user display for create new story -->

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}{% load static %}{% block stylesheets %}
{% endblock %}{% block content %}

<div id="story-wrapper">
  {% if story.author == request.user %}
  <div class="story-buttons">
    <a href=" {% url 'news:editStory' story.id %}" class="accent-button">Edit Story</a>
    <a href=" {% url 'news:deleteStory' story.id %}" class="accent-button ">Delete Story</a>
  </div>
  {% endif %}

  <h2>{{ story.title }}</h2>
  
  <div id="story-content">
    {% if not story.image_url %}
      <img src="https://picsum.photos/600">
    {% else %}
      <img src="{{ story.image_url }}" />
    {% endif %}
    <p>{{ story.content|linebreaks }}</p>
  </div>
  <a href="{% url 'users:profile' story.author.id %}" class="story-author">Written by {{ story.author }}</a>
  <a href='{% url "news:category" story.category %}' class="category-button accent-button">{{ story.category }}</a>
</div>
<div class="likes-and-favourites">
<p>Liked by {{ story.liked_by.count }}</p>
<p>
  {% if request.user.is_authenticated %}
  <a href="{% url 'news:like' story.id %}">
    {% if user in story.liked_by.all %}<i class="fa-solid fa-thumbs-up"></i> Liked{% else %}<i class="fa-regular fa-thumbs-up fa-large"></i> Like this post{% endif %}</a></p>
<p><a href="{% url 'news:favourite_post' story.id %}">{% if user in story.favourite.all %}<i class="fa-solid fa-heart fa-large"></i> Added to favourites{% else %}<i class="fa-regular fa-heart fa-large"></i> Add to favourites{% endif %}</a></p>
{% else %}
<p>Log in to like or favourite this post</p>
{% endif %}
</div>
<div class="comments-wrapper">
  <h3>Comments</h3>
  {% if not story.comments.all %}
    <p>No comments yet</p>
    <a href="{% url 'news:addComment' story.id %}" class="accent-button">Add comment</a>
  {% else %}
    <a href="{% url 'news:addComment' story.id %}" class="accent-button">Add comment</a>
      {% for comment in story.comments.all %}
      <div class="comment-wrapper">
        <p class="comment-details">
          {{ comment.name }} - {{ comment.date_added }}
        </p>
        <p class="comment-body">
          {{ comment.body }}
        </p>
      </div>
    {% endfor %}
  {% endif %}
</div>

{% endblock %}

<!--views, url, html--> 

she_codes_news/news/templates/news/storyCard.html
{% extends "base.html" %} {% load static %} {% block stylesheets %}

{% endblock %} {% block content %}

<div class="story-card" id="story-card-{{ position }}">
  <a href="{% url 'news:story' story.id %}" class="story-card-link">
    {% if story.image_url != null %}
    <img src={{ story.image_url }} />
    {% else %}
    <img src="https://picsum.photos/600" />
    {% endif %}
    <div class="story-card-text">
      <p class="story-card-date">{{ story.pub_date }}</p>
      <h3>{{ story.title }}</h3> 
      <a href='{% url "news:category" story.category %}' class="story-card-category">{{ story.category }}</a>
      <a href="{% url 'users:profile' story.author.id %}" class="story-card-author">{{ story.author }}</a> 
    </div>
  </a>
</div>

{#{% url 'users:profile' request.user.id %}#}

{% endblock %}